export const languageD = [
  { code: "en", name: "English", bgColor: "#1E90FF", textColor: "#FFFFFF" }, // Blue background, white text
  { code: "es", name: "Spanish", bgColor: "#FFD700", textColor: "#000000" }, // Gold background, black text
  { code: "zh", name: "Chinese", bgColor: "#FF4500", textColor: "#FFFFFF" }, // OrangeRed background, white text
  { code: "hi", name: "Hindi", bgColor: "#32CD32", textColor: "#FFFFFF" }, // LimeGreen background, white text
  { code: "ar", name: "Arabic", bgColor: "#8B0000", textColor: "#FFFFFF" }, // DarkRed background, white text
  { code: "fr", name: "French", bgColor: "#4169E1", textColor: "#FFFFFF" }, // RoyalBlue background, white text
  { code: "ru", name: "Russian", bgColor: "#C71585", textColor: "#FFFFFF" }, // MediumVioletRed background, white text
  { code: "pt", name: "Portuguese", bgColor: "#228B22", textColor: "#FFFFFF" }, // ForestGreen background, white text
  { code: "de", name: "German", bgColor: "#FF6347", textColor: "#FFFFFF" }, // Tomato background, white text
  { code: "ja", name: "Japanese", bgColor: "#DC143C", textColor: "#FFFFFF" }, // Crimson background, white text
  { code: "ko", name: "Korean", bgColor: "#4682B4", textColor: "#FFFFFF" }, // SteelBlue background, white text
  { code: "it", name: "Italian", bgColor: "#008080", textColor: "#FFFFFF" }, // Teal background, white text
  { code: "bn", name: "Bengali", bgColor: "#FF1493", textColor: "#FFFFFF" }, // DeepPink background, white text
  { code: "pa", name: "Punjabi", bgColor: "#FFA500", textColor: "#000000" }, // Orange background, black text
  { code: "ur", name: "Urdu", bgColor: "#556B2F", textColor: "#FFFFFF" }, // DarkOliveGreen background, white text
  { code: "vi", name: "Vietnamese", bgColor: "#800080", textColor: "#FFFFFF" }, // Purple background, white text
  { code: "id", name: "Indonesian", bgColor: "#A52A2A", textColor: "#FFFFFF" }, // Brown background, white text
  { code: "tr", name: "Turkish", bgColor: "#FF69B4", textColor: "#FFFFFF" }, // HotPink background, white text
  { code: "fa", name: "Persian", bgColor: "#B22222", textColor: "#FFFFFF" }, // FireBrick background, white text
  { code: "ta", name: "Tamil", bgColor: "#4682B4", textColor: "#FFFFFF" }, // SteelBlue background, white text
  { code: "te", name: "Telugu", bgColor: "#9ACD32", textColor: "#000000" }, // YellowGreen background, black text
  { code: "mr", name: "Marathi", bgColor: "#FF4500", textColor: "#FFFFFF" }, // OrangeRed background, white text
  { code: "ml", name: "Malayalam", bgColor: "#00CED1", textColor: "#FFFFFF" }, // DarkTurquoise background, white text
  { code: "gu", name: "Gujarati", bgColor: "#9932CC", textColor: "#FFFFFF" }, // DarkOrchid background, white text
  { code: "kn", name: "Kannada", bgColor: "#FF6347", textColor: "#FFFFFF" }, // Tomato background, white text
  { code: "th", name: "Thai", bgColor: "#2E8B57", textColor: "#FFFFFF" }, // SeaGreen background, white text
  { code: "sw", name: "Swahili", bgColor: "#DAA520", textColor: "#000000" }, // GoldenRod background, black text
  { code: "ne", name: "Nepali", bgColor: "#DC143C", textColor: "#FFFFFF" }, // Crimson background, white text
  { code: "el", name: "Greek", bgColor: "#0000CD", textColor: "#FFFFFF" }, // MediumBlue background, white text
  { code: "ro", name: "Romanian", bgColor: "#FFD700", textColor: "#000000" }, // Gold background, black text
  { code: "pl", name: "Polish", bgColor: "#FF4500", textColor: "#FFFFFF" }, // OrangeRed background, white text
  { code: "uk", name: "Ukrainian", bgColor: "#1E90FF", textColor: "#FFFFFF" }, // DodgerBlue background, white text
  { code: "cs", name: "Czech", bgColor: "#8A2BE2", textColor: "#FFFFFF" }, // BlueViolet background, white text
  { code: "sv", name: "Swedish", bgColor: "#FFD700", textColor: "#000000" }, // Gold background, black text
  { code: "da", name: "Danish", bgColor: "#FF1493", textColor: "#FFFFFF" }, // DeepPink background, white text
  { code: "fi", name: "Finnish", bgColor: "#00BFFF", textColor: "#FFFFFF" }, // DeepSkyBlue background, white text
  { code: "no", name: "Norwegian", bgColor: "#4682B4", textColor: "#FFFFFF" }, // SteelBlue background, white text
  { code: "he", name: "Hebrew", bgColor: "#6A5ACD", textColor: "#FFFFFF" }, // SlateBlue background, white text
  { code: "hu", name: "Hungarian", bgColor: "#B22222", textColor: "#FFFFFF" }, // FireBrick background, white text
  { code: "nl", name: "Dutch", bgColor: "#FFA07A", textColor: "#000000" }, // LightSalmon background, black text
  { code: "am", name: "Amharic", bgColor: "#8B0000", textColor: "#FFFFFF" }, // DarkRed background, white text
];
